#+ endpoint: https://api.druid.datalegend.net/datasets/nlgis/cshapes/services/cshapes/sparql Auto-selected
#+ summary: retrieves the variables from CSHAPES in Linked Places tsv format
#+ method: GET
#+ pagination: 100
#+ tags:
#+   - WHGazetteer
#+   - Linked Places
#+   - CSHAPES
#+   - druid.daalegend.net

# for format see: https://github.com/LinkedPasts/linked-places/blob/master/tsv.md
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX iisgv: <https://iisg.amsterdam/vocab/>
PREFIX iisgd: <https://iisg.amsterdam/dataset/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?id ?title ?geom_source ?ccodes ?min ?max ?citation WHERE {
  
  # MUST-HAVE VARIABLES
  ?id rdf:type iisgv:CountrySlice .
  ?id iisgv:isoName ?title .
  iisgd:cshapes foaf:page ?geom_source .

  # OPTIONAL VARIABLES
  ?id iisgv:isoAlpha2 ?ccodes .
  ?id iisgv:cowStart ?min .
  ?id iisgv:cowEnd ?max .
  
  # SOURCE VARIABLES
  # not sure how 'id' and 'title' would differ from the ones above
  BIND("https://druid.datalegend.net/nlgis/cshapes/"^^xsd:anyURI as ?citation)
  
  # FILTER regex(str(?countryLabel), "^N", "i") # remove the '#' filter on countries starting with 'N' 
  # FILTER (?startCountry > "1990-01-01"^^xsd:date) # remove the '#' at the start of the line to filter on >1990
}
